### PR TITLE
Allow the window to be resized freely

### PR DESCRIPTION
**Pull request by smiegrin**
This is just a convenience that seemed easy to implement. If this clashes with the vision of this project, feel free to turn this PR down.

Of particular note, the way the window resizes doesn't seem to really keep the "Pixel" look of things -- some of the fonts look a tad blurry, and the backgrounds don't seem to upscale in a pixel-sensitive fashion.

### CODE REVIEW

**Comment by joezeng** [comment]
You might want to rebase the branch on current master. You’ve got the Survival A1 commit in there again.

**Comment by smiegrin** [comment]
Ah shoot, you're right...

**Comment by smiegrin** [comment]
Here, see if that works out. It's... been a while since I've worked with git to this depth. " ^ _^

**Comment by joezeng** [comment]
Yeah, this looks fine. Eventually in the config option there'll be a way to select your desired initial resolution, and choose whether you want Nearest or Bilinear filtering (Bilinear would look good at non-integer multiple scaling).

**Pull request merged**
